### ISSUE TITLE
MalformedCaptionError - After upgrade to 0.4.0

### ISSUE THREAD

**Issue by amrutauk** [glut23/webvtt-py#13]
Hi , I recently upgraded the package to 4.0 and started getting this error while reading the youtube VTT file.  And different file is giving different MalformedCaptionErrors . One has : 'Standalone cue identifier' error  while the other gets 'webvtt.exceptions.MalformedCaptionError: --> found in line 471' .  I did not face this issue with old version. 

Attaching a couple VTT files i'm trying to read for your reference. (since vtt file cannot be attached here , copied to text file)

[ NEW_ DELL Inspiron 15 5000 series 2-in-1 Unboxing!-2VioHGnyAG0.txt](https://github.com/glut23/webvtt-py/files/1354809/NEW_.DELL.Inspiron.15.5000.series.2-in-1.Unboxing.-2VioHGnyAG0.txt)
['Review' Dell Inspiron 15 5000 - 5559 _ Best video editing and gaming laptop review 2016-joCJVrcZnxM.en.txt](https://github.com/glut23/webvtt-py/files/1354811/Review.Dell.Inspiron.15.5000.-.5559._.Best.video.editing.and.gaming.laptop.review.2016-joCJVrcZnxM.en.txt)

Please let me know if you need more  info. 
Thanks !

**Comment by glut23** [comment]
Hi @amrutauk, the last version includes a new parser for WebVTT so it could give back different validation errors compared to old versions. I checked the captions you provided and found:
- First vtt file contains the string --> as part of the text in line 471. Specs of the format do not allow this and that is why it does not validate. It looks like that there are two captions missing a blank line between them.
- The second file in line 13 does not have a cue timing associated to the text. I see the problem is that it has a blank line between the cue timings and the text. Removing that blank like it parses well.

Hope this helps. Any feedback let me know.

Thanks!

**Comment by amrutauk** [comment]
Hi , I have downloaded these files using youtube-dl and looks like they aren't following the specs.  I have way too many files to edit them manually . Many files are throwing errors in the new version and I regret upgrading ! :( 

 Is there a way I can install the older version , 0.3.4 ? It was working really good for me ! Please Let me know .

Thanks !

**Comment by glut23** [comment]
Hi @amrutauk you can install the previous version 0.3.3 assuming you are using pip to install Python packages as follows:
pip install webvtt-py==0.3.3

I am going to consider updating validation rules for keeping as much compatibility as possible so you could use the latest release.

Let me know if you have any more issues.

Thanks!
