### ISSUE TITLE
Standalone cue identifier in line 7

### ISSUE THREAD

**Issue by amrutadotorg** [glut23/webvtt-py#53]
Hi, all validators are ok with the file.
Kindly please check. Thank you.
[1999-0624-Wie-wir-uns-zu-einer-besseren-Personlichkeit-entwickeln.vtt.zip](https://github.com/glut23/webvtt-py/files/13182841/1999-0624-Wie-wir-uns-zu-einer-besseren-Personlichkeit-entwickeln.vtt.zip)

**Comment by glut23** [comment]
Hi @amrutadotorg please provide the captions as plain text in a comment. But this error basically is raised when a line of text is found not being part of a block of lines with the expected format. In the recent latest release 0.5.0 the library now ignores the content that is not following the specs of WebVTT format instead of raising an exception. I am closing this issue but reopen if needed. Thanks.
